<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_INDOCYBER</name>
   <tag></tag>
   <elementGuidId>b27337ab-3bfe-4d48-8f3d-d145427e30c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@class = 'select2-results__option' and (text() = 'INDOCYBER' or . = 'INDOCYBER')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>309a506d-7203-4e6d-b673-80fc1bfd761c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option</value>
      <webElementGuid>05754935-8678-461e-9096-efdf6dec2672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INDOCYBER</value>
      <webElementGuid>952682d6-9e5e-4e33-9eb0-88c7cbaf794b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
