<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Choose Branch --</name>
   <tag></tag>
   <elementGuidId>a51e2b27-83fb-4648-ad52-ce9d3433a931</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-branchAdd-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-branchAdd-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-branchAdd-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cdd3b742-b130-4a08-8ba9-064c6a7c3708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>533f5521-f7e3-4d0c-a7ca-5c8a88c70db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-branchAdd-container</value>
      <webElementGuid>058e9bd9-7db4-4de8-80a0-832d1f1bacbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Choose Branch --</value>
      <webElementGuid>26f5afbb-23db-4b09-b937-512f41d93806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-branchAdd-container&quot;)</value>
      <webElementGuid>b029e60d-fc16-45b4-8670-5054057900e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-branchAdd-container']</value>
      <webElementGuid>fba8ced0-7009-4f3d-bad5-81c724d0e471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div/div[2]/div/span/span/span/span</value>
      <webElementGuid>3a9bc4b3-1175-4654-bd32-648726530f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch'])[3]/following::span[4]</value>
      <webElementGuid>58700a96-3eec-4c3a-a453-c8995a3c2fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INDOCYBER'])[9]/following::span[7]</value>
      <webElementGuid>28b71d5d-0dfc-4c49-bdb2-3b00c236ebc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question'])[3]/preceding::span[5]</value>
      <webElementGuid>d5ad5594-7e91-452b-b8fd-a0eaa500bcbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/span/span/span</value>
      <webElementGuid>4cf93c55-8d49-4889-9fe1-6744371e47b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-branchAdd-container' and (text() = '-- Choose Branch --' or . = '-- Choose Branch --')]</value>
      <webElementGuid>31acd85e-9f45-4572-b8ce-cf248098ca23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
