<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_Image_eLearning</name>
   <tag></tag>
   <elementGuidId>0e0dba75-1314-45d2-82d4-77d437e15938</elementGuidId>
   <imagePath>http://130.211.243.37:96/storage/images/logo/logo-elearning.svg</imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'http://130.211.243.37:96/storage/images/logo/logo-elearning.svg']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>http://130.211.243.37:96/storage/images/logo/logo-elearning.svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>79be8d0a-f1df-4604-82c0-a26b3be3f248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>285da769-bd0c-4ee1-9c25-372d53b8dad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://130.211.243.37:96/storage/images/logo/logo-elearning.svg</value>
      <webElementGuid>2d2531c7-1e9b-4d3d-b770-c499cacdba9c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
